### ISSUE TITLE
Rename repository from ritlug.github.io to ritlug.com

### ISSUE THREAD

**Issue by jflory7** [RITlug/ritlug.com#70]
With the advent of our new CNAME file in commit 3932d83ec0041b3eb8d77656b6475a6d47d6b280 (that should be propagated in another 16 minutes), I believe it makes sense for us to rename the repository from RITlug/ritlug.github.io to RITlug/ritlug.com for branding purposes.

@Serubin @thenaterhood @repkam09, thoughts?

**Comment by Serubin** [comment]
Sounds good.

**Comment by jflory7** [comment]
The deed hath been done! :clapper:
